### ISSUE TITLE
feature request: suppress reduction for multiple labels

### ISSUE THREAD

**Issue by regehr** [DRMacIver/structureshrink#2]
Any chance we can get a command line option that suppresses the multiple reductions? And only reduces for label 0? No big deal but this would permit me to do a head-to-head comparison against C-Reduce.

**Comment by DRMacIver** [comment]
Hmm. That should be quite easy to do. Let me have a look.

**Comment by DRMacIver** [comment]
OK, this should be fixed in 88b62a0cd40cf56da49f101c1a3ee8b9b5ed64f1. It adds the '--principal' flag which means that structureshrink will never go out of its way to shrink any label except for the one that the starting example had. It will still record any other shrinks it finds along the way, but it won't do any extra work to try to produce them.

This is heavily undertested but probably works. :-) Let me know if it gives you any problems.

**Comment by regehr** [comment]
Perfect, this is directly comparable to C-Reduce, will test it now.
